### ISSUE TITLE
Pull Request Validation Pipeline

### ISSUE THREAD

**Issue by gitaumoses4** [rhinolabs/rhino-ui#41]
**Is your feature request related to a problem? Please describe.**

It would be good to have  a Pull request pipeline that runs on each PR to `main` branch. 

**Describe the solution you'd like**
The pipeline should run the following tasks.
* Lint check
* Tests
* Build

**Comment by chrisllontop** [comment]
Hi @gitaumoses4, I'm working on the Chromatic pipeline to build the storybook and compare versions. 

So, this is our initial step to have PR pipelines with approval options.

**Comment by chrisllontop** [comment]
@gitaumoses4 Could we add to the pipeline other tasks in parallel? for example, run prettier and eslint commands (Check #52 )

**Comment by gitaumoses4** [comment]
Yes @chrisllontop , the "Lint Checks" are essentially tied to running the eslint and prettier configurations.
