### ISSUE TITLE
Main Branch CI Pipeline

### ISSUE THREAD

**Issue by gitaumoses4** [rhinolabs/rhino-ui#42]
**Is your feature request related to a problem? Please describe.**
It would be good to have a Pipeline that runs on any new commit to the `main` branch

**Describe the solution you'd like**
The Pipeline should execute the following tasks.

* Lint check
* Tests
* Build

**Comment by chrisllontop** [comment]
I think that this is redundant with the merge pipeline. I'll close it. Thanks! @gitaumoses4
