### ISSUE TITLE
Enable modular import pattern for component efficiency

### ISSUE THREAD

**Issue by chrisllontop** [rhinolabs/rhino-ui#48]
**Is your feature request related to a problem? Please describe.**
The issue arises from our current export pattern in `index.js`, leading to the entire library's inclusion in the project bundle, even if only a few components are used. This can significantly increase the bundle size, impacting application performance.

**Describe the solution you'd like**
I suggest introducing a modular import option that allows importing components directly from their subpaths, alongside our existing aggregate export approach. For example:
- Direct import: `import Alert from '@rhino-ui/components/alert'`
- Aggregate import: `import { Alert } from '@rhino-ui/components'`

This dual approach reduces the bundle size by including only the necessary components, aligning with performance optimization practices. It requires adjusting our package structure to support individual component exports, offering a significant performance benefit without sacrificing convenience.

**Comment by gitaumoses4** [comment]
While at this, it would be good to look into modular package option. 

`npm install @rhino-ui/alert` 

That is having each component into it's own package, that can be installed independently.

**Comment by chrisllontop** [comment]
For design we want to keep using only one package for components due we have packages like @rhino-ui/hooks or @rhino-ui/components, etc. 

But we want to offer modular imports into, for this reason I’m proposing this. Thoughts?

**Comment by gitaumoses4** [comment]
An approach to achieve this is to update our existing vite config to include every component's path as an individual entry point. 
This will help us achieve the goal of compiling each component individually, and having the component easily imported as follows.

`import Alert from '@rhino-ui/components/alert'`

**Comment by gitaumoses4** [comment]
This is what we have currently.

The aggregate import is a bundle of ~500kB

![image](https://github.com/rhinolabs/rhino-ui/assets/25629064/900bf946-a182-4ba4-8013-bb2fb0d5b40a)

**Comment by gitaumoses4** [comment]
Vite build looks as follows.
![image](https://github.com/rhinolabs/rhino-ui/assets/25629064/cce30cc2-0d91-47fa-a478-bade055641cb)
